on:
  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
      - "test/*.go"
name: terratest
jobs:
  terratest:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version: "1.22.x"
      - uses: "google-github-actions/auth@62cf5bd3e4211a0a0b51f2c6d6a37129d828611d" # v2
        with:
          project_id: "library-344516"
          workload_identity_provider: "projects/270410071403/locations/global/workloadIdentityPools/github/providers/padok-gcp-library"
      - name: tfswitch
        run: |
          wget https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh
          chmod 755 install.sh
          ./install.sh -b ./.bin v1.2.2 # Last arg is the desired tfswitch version
          rm install.sh
          .bin/tfswitch -b .bin/terraform
          .bin/terraform -v
      - name: Test with the Go CLI
        run: go test -timeout 30s ./test
